
name: 👷 Metrics
on:
  schedule: [{cron: "0 0 * * *"}]
  workflow_dispatch:
  push: {branches: ["main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
    - name: Activity
      uses: lowlighter/metrics@latest
      with:
        filename: metrics.classic.svg
        token: ${{ secrets.METRICS_TOKEN }}
        base: ""
        plugin_habits: yes
        plugin_habits_facts: yes
        plugin_habits_charts: no
        config_timezone: Asia/Bangkok
        plugin_languages: yes
        plugin_languages_indepth: yes
        plugin_languages_details: lines, bytes-size
        plugin_activity: yes
        plugin_activity_limit: 10
        plugin_activity_days: 7
        plugin_activity_filter: all
