
name: 👷 Update Contribution Metrics
on:
  schedule: [{cron: "0 0 * * *"}]
  workflow_dispatch:
  push: {branches: ["main"]}
jobs:
  self-hosted:
    name: 🪸 Update Contribution Metrics - Self-hosted
    runs-on: [self-hosted, linux, low-power]
    steps:
    - name: Activity
      uses: lowlighter/metrics@latest
      with:
        filename: metrics.classic.svg
        token: ${{ secrets.METRICS_TOKEN }}
        base: ""
        plugin_habits: yes
        plugin_habits_facts: yes
        plugin_habits_charts: yes
        config_timezone: Asia/Bangkok
        plugin_languages: yes
        plugin_languages_indepth: yes
        plugin_languages_details: lines, bytes-size
  githuh-actions:
    name: 🪸 Update Contribution Metrics - GitHub Actions
    if: ${{ failure() }}
    runs-on: ubuntu-latest
    steps:
    - name: Activity
      uses: lowlighter/metrics@latest
      with:
        filename: metrics.classic.svg
        token: ${{ secrets.METRICS_TOKEN }}
        base: ""
        plugin_habits: yes
        plugin_habits_facts: yes
        plugin_habits_charts: yes
        config_timezone: Asia/Bangkok
        plugin_languages: yes
        plugin_languages_indepth: yes
        plugin_languages_details: lines, bytes-size
