
name: Metrics
on:
  schedule: [{cron: "0 0 * * *"}]
  workflow_dispatch:
  push: {branches: ["main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
    - name: Recent activity
      uses: lowlighter/metrics@latest
      with:
        filename: metrics.classic.svg
        token: ${{ secrets.METRICS_TOKEN }}
        base: ""
        plugin_activity: yes
        plugin_activity_limit: 10
        plugin_activity_days: 7
        plugin_activity_filter: all
